---
- name: install tomcat
  package:
    name: tomcat
    state: latest
- name: enable tomcat at boot
  service:
    name: tomcat
    enabled: yes
- name: create tomcat ansible directory
  file:
    path: /usr/share/tomcat/webapps/ROOT
    state: directory
- name: copy index.html to tomcat webapps/ROOT/index.html
  template:
    src: templates/index.html.j2
    dest: /usr/share/tomcat/webapps/ROOT/index.html
    mode: 0644
- name: start tomcat
  service:
    name: tomcat
    state: started
